#!/usr/bin/perl -w
#
# Quick hack to discover undocumented primitives.
#
# NOTE: This assumes you have a copy of lumail checked out into:
#       ~/git/lumail/
#
# Steve
# --
#

use strict;
use warnings;


#
# Get the home directory
#
my $home = $ENV{ 'HOME' };

#
# Ensure lumail is present.
#
if ( !-d "$home/git/lumail" )
{
    print "~/git/lumail is not present.  Aborting.\n";
    exit 1;
}


#
#  Open the binding-file
#
open( my $handle, "<", $home . "/git/lumail/lua.cc" ) or
  die "Failed to open binding file - $!";

#
# Read each line
#
while ( my $line = <$handle> )
{

    #
    # Look for calls to the lua-function registration method
    #
    if ( $line =~ /lua_register\((.*)\);/ )
    {

        #
        # "Parse"
        #
        my $reg = $1;
        my @ents = split( /,/, $reg );

        # The lua handle, the name of the function, and the C-implementation method.
        my $lua  = $ents[0];
        my $name = $ents[1];
        my $c    = $ents[2];

        # strip " and whitespace
        $name =~ s/^\s+|\s+$//g;
        $name =~ s/"//g;

        #
        # If there is no matching documentation file, then it is
        # a function that is undocumented.
        #
        if ( !-e "./input/lua/$name.tmplr" )
        {
            print "undocumented primitive: $name\n";
        }
    }
}
close($handle);

#
# All done.
#
exit 0;
