#!/usr/bin/perl -w
#
# Quick hack to discover undocumented primitives.
#
# NOTE: This assumes you have a copy of lumail checked out into:
#       ~/git/lumail/
#
# Steve
# --
#

use strict;
use warnings;


#
#  Show functions if called with any arguments.
#
my $DEBUG = shift;


#
# Get the home directory
#
my $home = $ENV{ 'HOME' };

#
# Ensure lumail is present.
#
if ( !-d "$home/git/lumail" )
{
    print "~/git/lumail is not present.  Aborting.\n";
    exit 1;
}


#
#  Open the binding-file
#
open( my $handle, "<", $home . "/git/lumail/src/lua.cc" ) or
  die "Failed to open binding file - $!";

#
# Read each line
#
while ( my $line = <$handle> )
{

    #
    # Look for calls to the lua-function registration method
    #
    next unless( $line =~ /CFunction/ );

    if ( $line =~ /"([^"]+)"\S*,\s*([^}]+)}/ )
    {

        #
        # "Parse"
        #
        my $lua = $1;
        my $c   = $2;
        $c =~ s/\(lua_CFunction\)//g;
        $c =~ s/^\s+|\s+$//g;


        $DEBUG && print "Lua: $lua -> $c\n";

        #
        # If there is no matching documentation file, then it is
        # a function that is undocumented.
        #
        if ( !-e "./input/lua/$lua.tmplr" )
        {
            print "undocumented primitive: $lua\n";
        }
    }
}
close($handle);

#
# All done.
#
exit 0;
