<dl>
   <dt>24th June 2016</dt>
     <dd><p>Version 2.6 of Lumail is now available upon our <a href="/download/">download page</a>.</p>
         <p>This release improves the display-handling, adds some minor bugfixes, and introduces an integrated set of (self)test-cases.</p>
     </dd>
   <dt>2nd February 2016</dt>
     <dd><p>A new release of Lumail 2 is available upon our <a href="/download/">download page</a>.</p>
         <p>This release improves <a href="/imap/">IMAP</a> performance, adds support for
   line-wrapping, and improves the display of coloured emails.</p>
     </dd>
</dl>
<p class="right"><a href="/news/">Archived news</a> is available for posterity.</p>
<p>&nbsp;</p>
