  <dl>
    <dt>16th September 2014</dt>
    <dd>
    <p>Lumail 0.26 has been released and <a href="/download/">is available for download</a>.  This release adds multiple minor bugfixes, and features including the ability to support multiple Maildir prefixes, and the support for wrapping headers.</p></dd>
    <dt>14th May 2014</dt>
    <dd>
    <p>Lumail 0.25 has been released and <a href="/download/">is available for download</a>.  This release adds a new mode to the client, the ability to show text from a file (<a href="/lua/show_file_contents.html"><tt>show_file_contents()</tt></a>) or programatically (<a href="/lua/show_text.html"><tt>show_text()</tt></a>).</p>
    <p>There were several bugfixes relating to TAB-completion, and new features relating to the current working-directory (<a href="/lua/cd.html"><tt>cd()</tt></a>, <a href="/lua/cwd.html"><tt>cwd()</tt></a>), along with support for reading arbitrary lua via <a href="/docs/external-input.html">a Unix domain-socket</a>.</p>
    </dd>
    <dt>18th Janaury 2014</dt>
    <dd>
    <p>This release contains several bug-fixes relating to handling oddly formed messages, and updates some of the primitives such as <a href="/lua/hostname.html">hostname()</a> which may now be overridden.</p>
    <p>The command-line handling was improved, and the <a href="/lua/clear.html">clear()</a> primitive will now work correctly in all circumstances.</p>
    </dd>
    <dt>13th October 2013</dt>
    <dd>
    <p>This release contains only minor changes, but these changes improve the speed of handling large mailboxes, and large directories.</p>
    <p>The only significant new functionality is the introduction of the <a href="/lua/hostname.html">hostname()</a> primitive.</p></dd>
  </dl>
 <p class="right"><a href="/news/">Archived news</a> is available for posterity.</p>
 <p>&nbsp;</p>
